version: "3.9"

services:
  platform:
    build: .
    image: practice-platform
    command: gunicorn --bind 0.0.0.0:80 --access-logfile - --error-logfile -
      --reload django_training.wsgi
    env_file:
      - local.env
    ports:
      - "8000:80"
    volumes:
      - ./:/app

  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=03041999
      - POSTGRES_DB=student_manager
    volumes:
      - pg-volume:/var/lib/postgresql/data/
    ports:
      - "5432:5432"


volumes:
  pg-volume:
