# Generated by Django 3.2.8 on 2022-05-30 08:45

from django.db import migrations, models
import django.utils.timezone
import student_manager.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='old_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_code',
            field=models.CharField(default=student_manager.users.models.generate_otp, max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
