# Generated by Django 4.0.4 on 2022-06-01 06:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220530_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=20)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2022, 6, 1, 6, 53, 53, 102585, tzinfo=utc))),
                ('updated_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
