# Generated by Django 4.0.4 on 2022-06-01 09:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_mobileotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 1, 9, 24, 41, 119531, tzinfo=utc)),
        ),
    ]
