# Generated by Django 4.0.4 on 2022-06-02 04:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_mobileotp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mobileotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 4, 51, 33, 98416, tzinfo=utc)),
        ),
    ]
