# Generated by Django 4.0.4 on 2022-06-02 04:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_active_alter_mobileotp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='mobileotp',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 4, 57, 8, 733714, tzinfo=utc)),
        ),
    ]
