# Generated by Django 4.0.4 on 2022-06-02 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_date_joined_alter_mobileotp_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileotp',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
