# Generated by Django 3.2.8 on 2022-05-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
